# Start from our pre-built base image, which contains all heavy dependencies.
FROM mynaparrot/plugnmeet-server:base

# Align with production: Environment variables
ENV SPEECHSDK_ROOT="/opt/speechsdk"

WORKDIR /app

# Cache Go modules
COPY go.mod go.sum ./
RUN go mod download

# Entrypoint script
COPY docker-build/docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["air"]
