// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"context"
	"github.com/google/wire"
	"github.com/mynaparrot/plugnmeet-server/pkg/config"
	"github.com/mynaparrot/plugnmeet-server/pkg/controllers"
	"github.com/mynaparrot/plugnmeet-server/pkg/models"
	"github.com/mynaparrot/plugnmeet-server/pkg/services/db"
	"github.com/mynaparrot/plugnmeet-server/pkg/services/livekit"
	"github.com/mynaparrot/plugnmeet-server/pkg/services/nats"
	"github.com/mynaparrot/plugnmeet-server/pkg/services/redis"
)

// Injectors from wire.go:

// NewAppFactory is the injector function that wire will implement.
func NewAppFactory(appConfig *config.AppConfig) (*Application, error) {
	client := appConfig.RDS
	redisService := redisservice.New(client)
	db := appConfig.DB
	databaseService := dbservice.New(db)
	natsService := natsservice.New(appConfig)
	livekitService := livekitservice.New(appConfig)
	applicationServices := &ApplicationServices{
		RedisService:    redisService,
		DatabaseService: databaseService,
		NatsService:     natsService,
		LivekitService:  livekitService,
	}
	analyticsModel := models.NewAnalyticsModel(appConfig, databaseService, redisService)
	authModel := models.NewAuthModel(appConfig, natsService)
	bbbApiWrapperModel := models.NewBBBApiWrapperModel(appConfig, databaseService, redisService)
	breakoutRoomModel := models.NewBreakoutRoomModel(appConfig, databaseService, redisService)
	roomDurationModel := models.NewRoomDurationModel(appConfig, redisService)
	etherpadModel := models.NewEtherpadModel(appConfig, databaseService, redisService)
	exDisplayModel := models.NewExDisplayModel(appConfig, databaseService, redisService)
	exMediaModel := models.NewExMediaModel(appConfig, databaseService, redisService)
	fileModel := models.NewFileModel(appConfig, databaseService, natsService)
	ingressModel := models.NewIngressModel(appConfig, databaseService, redisService, livekitService)
	ltiV1Model := models.NewLtiV1Model(appConfig, databaseService, redisService)
	natsModel := models.NewNatsModel(appConfig, databaseService, redisService)
	pollModel := models.NewPollModel(appConfig, databaseService, redisService)
	recorderModel := models.NewRecorderModel(appConfig, databaseService, redisService)
	recordingModel := models.NewRecordingModel(appConfig, databaseService, redisService)
	roomModel := models.NewRoomModel(appConfig, databaseService, redisService)
	schedulerModel := models.NewSchedulerModel(appConfig, databaseService, redisService)
	speechToTextModel := models.NewSpeechToTextModel(appConfig, databaseService, redisService)
	userModel := models.NewUserModel(appConfig, databaseService, redisService)
	waitingRoomModel := models.NewWaitingRoomModel(appConfig, redisService)
	context := provideContext()
	webhookModel := models.NewWebhookModel(context, appConfig, databaseService, redisService)
	applicationModels := &ApplicationModels{
		AnalyticsModel:     analyticsModel,
		AuthModel:          authModel,
		BBBApiWrapperModel: bbbApiWrapperModel,
		BreakoutRoomModel:  breakoutRoomModel,
		RoomDurationModel:  roomDurationModel,
		EtherpadModel:      etherpadModel,
		ExDisplayModel:     exDisplayModel,
		ExMediaModel:       exMediaModel,
		FileModel:          fileModel,
		IngressModel:       ingressModel,
		LtiV1Model:         ltiV1Model,
		NatsModel:          natsModel,
		PollModel:          pollModel,
		RecorderModel:      recorderModel,
		RecordingModel:     recordingModel,
		RoomModel:          roomModel,
		SchedulerModel:     schedulerModel,
		SpeechToTextModel:  speechToTextModel,
		UserModel:          userModel,
		WaitingRoomModel:   waitingRoomModel,
		WebhookModel:       webhookModel,
	}
	analyticsController := controllers.NewAnalyticsController(analyticsModel)
	authController := controllers.NewAuthController(appConfig, authModel, roomModel, natsService)
	bbbController := controllers.NewBBBController(appConfig, roomModel, userModel, bbbApiWrapperModel, recordingModel, natsService)
	breakoutRoomController := controllers.NewBreakoutRoomController(breakoutRoomModel)
	etherpadController := controllers.NewEtherpadController(appConfig, etherpadModel, roomModel, databaseService)
	exDisplayController := controllers.NewExDisplayController(exDisplayModel)
	exMediaController := controllers.NewExMediaController(exMediaModel)
	fileController := controllers.NewFileController(appConfig, fileModel)
	ingressController := controllers.NewIngressController(ingressModel)
	ltiV1Controller := controllers.NewLtiV1Controller(ltiV1Model, roomModel, recordingModel)
	pollsController := controllers.NewPollsController(pollModel, redisService)
	recorderController := controllers.NewRecorderController(appConfig, recorderModel, recordingModel, roomModel, databaseService)
	recordingController := controllers.NewRecordingController(recordingModel)
	roomController := controllers.NewRoomController(roomModel)
	speechToTextController := controllers.NewSpeechToTextController(speechToTextModel)
	userController := controllers.NewUserController(appConfig, userModel, databaseService, natsService)
	waitingRoomController := controllers.NewWaitingRoomController(waitingRoomModel)
	webhookController := controllers.NewWebhookController(authModel, webhookModel)
	natsController := controllers.NewNatsController(appConfig, authModel, natsModel)
	applicationControllers := &ApplicationControllers{
		AnalyticsController:    analyticsController,
		AuthController:         authController,
		BBBController:          bbbController,
		BreakoutRoomController: breakoutRoomController,
		EtherpadController:     etherpadController,
		ExDisplayController:    exDisplayController,
		ExMediaController:      exMediaController,
		FileController:         fileController,
		IngressController:      ingressController,
		LtiV1Controller:        ltiV1Controller,
		PollsController:        pollsController,
		RecorderController:     recorderController,
		RecordingController:    recordingController,
		RoomController:         roomController,
		SpeechToTextController: speechToTextController,
		UserController:         userController,
		WaitingRoomController:  waitingRoomController,
		WebhookController:      webhookController,
		NatsController:         natsController,
	}
	application := &Application{
		Services:    applicationServices,
		Models:      applicationModels,
		Controllers: applicationControllers,
		AppConfig:   appConfig,
		Ctx:         context,
	}
	return application, nil
}

// wire.go:

func provideContext() context.Context {
	return context.Background()
}

// build the dependency set for services
var serviceSet = wire.NewSet(dbservice.New, redisservice.New, natsservice.New, livekitservice.New)

// build the dependency set for models
var modelSet = wire.NewSet(models.NewAnalyticsModel, models.NewAuthModel, models.NewBBBApiWrapperModel, models.NewBreakoutRoomModel, models.NewRoomDurationModel, models.NewEtherpadModel, models.NewExDisplayModel, models.NewExMediaModel, models.NewFileModel, models.NewIngressModel, models.NewLtiV1Model, models.NewNatsModel, models.NewPollModel, models.NewRecorderModel, models.NewRecordingModel, models.NewRoomModel, models.NewSchedulerModel, models.NewSpeechToTextModel, models.NewUserModel, models.NewWaitingRoomModel, models.NewWebhookModel)

// build the dependency set for controllers
var controllerSet = wire.NewSet(controllers.NewAnalyticsController, controllers.NewAuthController, controllers.NewBBBController, controllers.NewBreakoutRoomController, controllers.NewEtherpadController, controllers.NewExDisplayController, controllers.NewExMediaController, controllers.NewFileController, controllers.NewIngressController, controllers.NewLtiV1Controller, controllers.NewPollsController, controllers.NewRecorderController, controllers.NewRecordingController, controllers.NewRoomController, controllers.NewSpeechToTextController, controllers.NewUserController, controllers.NewWaitingRoomController, controllers.NewWebhookController, controllers.NewNatsController)
