package azure

import "github.com/mynaparrot/plugnmeet-protocol/plugnmeet"

// supportedLanguages holds the static list of languages for Azure services.
// The key is the service name (e.g., "transcription", "translation").
var supportedLanguages = map[string][]plugnmeet.InsightsSupportedLangInfo{
	"transcription": {
		{Code: "af-ZA", Name: "Afrikaans", Locale: "af"},
		{Code: "am-ET", Name: "Amharic", Locale: "am"},
		{Code: "ar-AE", Name: "Arabic (United Arab Emirates)", Locale: "ar"},
		{Code: "ar-BH", Name: "Arabic (Bahrain)", Locale: "ar"},
		{Code: "ar-DZ", Name: "Arabic (Algeria)", Locale: "ar"},
		{Code: "ar-EG", Name: "Arabic (Egypt)", Locale: "ar"},
		{Code: "ar-IL", Name: "Arabic (Israel)", Locale: "ar"},
		{Code: "ar-IQ", Name: "Arabic (Iraq)", Locale: "ar"},
		{Code: "ar-JO", Name: "Arabic (Jordan)", Locale: "ar"},
		{Code: "ar-KW", Name: "Arabic (Kuwait)", Locale: "ar"},
		{Code: "ar-LB", Name: "Arabic (Lebanon)", Locale: "ar"},
		{Code: "ar-LY", Name: "Arabic (Libya)", Locale: "ar"},
		{Code: "ar-MA", Name: "Arabic (Morocco)", Locale: "ar"},
		{Code: "ar-OM", Name: "Arabic (Oman)", Locale: "ar"},
		{Code: "ar-PS", Name: "Arabic (Palestinian Territories)", Locale: "ar"},
		{Code: "ar-QA", Name: "Arabic (Qatar)", Locale: "ar"},
		{Code: "ar-SA", Name: "Arabic (Saudi Arabia)", Locale: "ar"},
		{Code: "ar-SY", Name: "Arabic (Syria)", Locale: "ar"},
		{Code: "ar-TN", Name: "Arabic (Tunisia)", Locale: "ar"},
		{Code: "ar-YE", Name: "Arabic (Yemen)", Locale: "ar"},
		{Code: "az-AZ", Name: "Azerbaijani", Locale: "az"},
		{Code: "hy-AM", Name: "Armenian", Locale: "hy"},
		{Code: "sq-AL", Name: "Albanian", Locale: "sq"},
		{Code: "bg-BG", Name: "Bulgarian", Locale: "bg"},
		{Code: "bn-IN", Name: "Bengali (India)", Locale: "bn"},
		{Code: "bs-BA", Name: "Bosnian", Locale: "bs"},
		{Code: "eu-ES", Name: "Basque", Locale: "eu"},
		{Code: "my-MM", Name: "Burmese", Locale: "my"},
		{Code: "ca-ES", Name: "Catalan", Locale: "ca"},
		{Code: "cs-CZ", Name: "Czech", Locale: "cs"},
		{Code: "hr-HR", Name: "Croatian", Locale: "hr"},
		{Code: "zh-CN", Name: "Chinese (Mandarin, Simplified)", Locale: "zh-Hans"},
		{Code: "wuu-CN", Name: "Chinese (Wu, Simplified)", Locale: "zh-Hans"},
		{Code: "zh-CN-shandong", Name: "Chinese (Jilu Mandarin, Simplified)", Locale: "zh-Hans"},
		{Code: "zh-CN-sichuan", Name: "Chinese (Southwestern Mandarin, Simplified)", Locale: "zh-Hans"},
		{Code: "zh-TW", Name: "Chinese (Taiwanese Mandarin)", Locale: "zh-Hant"},
		{Code: "yue-CN", Name: "Chinese (Cantonese, Simplified)", Locale: "zh-Hant"},
		{Code: "zh-HK", Name: "Chinese (Cantonese, Traditional)", Locale: "zh-Hant"},
		{Code: "da-DK", Name: "Danish", Locale: "da"},
		{Code: "nl-BE", Name: "Dutch (Belgium)", Locale: "nl"},
		{Code: "nl-NL", Name: "Dutch (Netherlands)", Locale: "nl"},
		{Code: "en-AU", Name: "English (Australia)", Locale: "en"},
		{Code: "en-US", Name: "English (US)", Locale: "en"},
		{Code: "en-GB", Name: "English (UK)", Locale: "en"},
		{Code: "en-CA", Name: "English (Canada)", Locale: "en"},
		{Code: "en-GH", Name: "English (Ghana)", Locale: "en"},
		{Code: "en-HK", Name: "English (Hong Kong SAR)", Locale: "en"},
		{Code: "en-IE", Name: "English (Ireland)", Locale: "en"},
		{Code: "en-IN", Name: "English (India)", Locale: "en"},
		{Code: "en-KE", Name: "English (Kenya)", Locale: "en"},
		{Code: "en-NG", Name: "English (Nigeria)", Locale: "en"},
		{Code: "en-NZ", Name: "English (New Zealand)", Locale: "en"},
		{Code: "en-PH", Name: "English (Philippines)", Locale: "en"},
		{Code: "en-SG", Name: "English (Singapore)", Locale: "en"},
		{Code: "en-TZ", Name: "English (Tanzania)", Locale: "en"},
		{Code: "en-ZA", Name: "English (South Africa)", Locale: "en"},
		{Code: "et-EE", Name: "Estonian", Locale: "et"},
		{Code: "fi-FI", Name: "Finnish", Locale: "fi"},
		{Code: "fil-PH", Name: "Filipino", Locale: "fil"},
		{Code: "fr-FR", Name: "French (France)", Locale: "fr"},
		{Code: "fr-BE", Name: "French (Belgium)", Locale: "fr"},
		{Code: "fr-CA", Name: "French (Canada)", Locale: "fr"},
		{Code: "fr-CH", Name: "French (Switzerland)", Locale: "fr"},
		{Code: "gl-ES", Name: "Galician", Locale: "gl"},
		{Code: "el-GR", Name: "Greek", Locale: "el"},
		{Code: "de-DE", Name: "German (Germany)", Locale: "de"},
		{Code: "de-CH", Name: "German (Switzerland)", Locale: "de"},
		{Code: "de-AT", Name: "German (Austria)", Locale: "de"},
		{Code: "ka-GE", Name: "Georgian", Locale: "ka"},
		{Code: "he-IL", Name: "Hebrew", Locale: "he"},
		{Code: "hi-IN", Name: "Hindi (India)", Locale: "hi"},
		{Code: "gu-IN", Name: "Gujarati (India)", Locale: "gu"},
		{Code: "kn-IN", Name: "Kannada (India)", Locale: "kn"},
		{Code: "ml-IN", Name: "Malayalam (India)", Locale: "ml"},
		{Code: "mr-IN", Name: "Marathi (India)", Locale: "mr"},
		{Code: "ta-IN", Name: "Tamil (India)", Locale: "ta"},
		{Code: "te-IN", Name: "Telugu (India)", Locale: "te"},
		{Code: "ga-IE", Name: "Irish", Locale: "ga"},
		{Code: "it-IT", Name: "Italian (Italy)", Locale: "it"},
		{Code: "it-CH", Name: "Italian (Switzerland)", Locale: "it"},
		{Code: "id-ID", Name: "Indonesian", Locale: "id"},
		{Code: "is-IS", Name: "Icelandic", Locale: "is"},
		{Code: "ja-JP", Name: "Japanese", Locale: "ja"},
		{Code: "jv-ID", Name: "Javanese", Locale: "jv"},
		{Code: "kk-KZ", Name: "Kazakh", Locale: "kk"},
		{Code: "km-KH", Name: "Khmer", Locale: "km"},
		{Code: "ko-KR", Name: "Korean", Locale: "ko"},
		{Code: "lo-LA", Name: "Lao", Locale: "lo"},
		{Code: "lt-LT", Name: "Lithuanian", Locale: "lt"},
		{Code: "lv-LV", Name: "Latvian", Locale: "lv"},
		{Code: "mk-MK", Name: "Macedonian", Locale: "mk"},
		{Code: "mn-MN", Name: "Mongolian", Locale: "mn"},
		{Code: "ms-MY", Name: "Malay", Locale: "ms"},
		{Code: "mt-MT", Name: "Maltese", Locale: "mt"},
		{Code: "nb-NO", Name: "Norwegian Bokmål", Locale: "nb"},
		{Code: "ne-NP", Name: "Nepali", Locale: "ne"},
		{Code: "pl-PL", Name: "Polish", Locale: "pl"},
		{Code: "ps-AF", Name: "Pashto", Locale: "ps"},
		{Code: "fa-IR", Name: "Persian", Locale: "fa"},
		{Code: "pt-BR", Name: "Portuguese (Brazil)", Locale: "pt"},
		{Code: "pt-PT", Name: "Portuguese (Portugal)", Locale: "pt"},
		{Code: "ro-RO", Name: "Romanian", Locale: "ro"},
		{Code: "ru-RU", Name: "Russian", Locale: "ru"},
		{Code: "si-LK", Name: "Sinhala", Locale: "si"},
		{Code: "es-ES", Name: "Spanish (Spain)", Locale: "es"},
		{Code: "es-MX", Name: "Spanish (Mexico)", Locale: "es"},
		{Code: "es-AR", Name: "Spanish (Argentina)", Locale: "es"},
		{Code: "es-BO", Name: "Spanish (Bolivia)", Locale: "es"},
		{Code: "es-CL", Name: "Spanish (Chile)", Locale: "es"},
		{Code: "es-CO", Name: "Spanish (Colombia)", Locale: "es"},
		{Code: "es-CR", Name: "Spanish (Costa Rica)", Locale: "es"},
		{Code: "es-CU", Name: "Spanish (Cuba)", Locale: "es"},
		{Code: "es-DO", Name: "Spanish (Dominican Republic)", Locale: "es"},
		{Code: "es-EC", Name: "Spanish (Ecuador)", Locale: "es"},
		{Code: "es-GQ", Name: "Spanish (Equatorial Guinea)", Locale: "es"},
		{Code: "es-GT", Name: "Spanish (Guatemala)", Locale: "es"},
		{Code: "es-HN", Name: "Spanish (Honduras)", Locale: "es"},
		{Code: "es-NI", Name: "Spanish (Nicaragua)", Locale: "es"},
		{Code: "es-PA", Name: "Spanish (Panama)", Locale: "es"},
		{Code: "es-PE", Name: "Spanish (Peru)", Locale: "es"},
		{Code: "es-PR", Name: "Spanish (Puerto Rico)", Locale: "es"},
		{Code: "es-PY", Name: "Spanish (Paraguay)", Locale: "es"},
		{Code: "es-SV", Name: "Spanish (El Salvador)", Locale: "es"},
		{Code: "es-US", Name: "Spanish (United States)", Locale: "es"},
		{Code: "es-UY", Name: "Spanish (Uruguay)", Locale: "es"},
		{Code: "es-VE", Name: "Spanish (Venezuela)", Locale: "es"},
		{Code: "sk-SK", Name: "Slovak", Locale: "sk"},
		{Code: "sl-SI", Name: "Slovenian", Locale: "sl"},
		{Code: "so-SO", Name: "Somali", Locale: "so"},
		{Code: "sr-RS", Name: "Serbian", Locale: "sr-Cyrl"},
		{Code: "sv-SE", Name: "Swedish", Locale: "sv"},
		{Code: "sw-KE", Name: "Swahili (Kenya)", Locale: "sw"},
		{Code: "sw-TZ", Name: "Swahili (Tanzania)", Locale: "sw"},
		{Code: "th-TH", Name: "Thai", Locale: "th"},
		{Code: "tr-TR", Name: "Turkish", Locale: "tr"},
		{Code: "uk-UA", Name: "Ukrainian", Locale: "uk"},
		{Code: "uz-UZ", Name: "Uzbek", Locale: "uz"},
		{Code: "vi-VN", Name: "Vietnamese", Locale: "vi"},
		{Code: "cy-GB", Name: "Welsh", Locale: "cy"},
		{Code: "zu-ZA", Name: "Zulu", Locale: "zu"},
	},
	"translation": {
		{Code: "af", Name: "Afrikaans"},
		{Code: "sq", Name: "Albanian"},
		{Code: "am", Name: "Amharic"},
		{Code: "ar", Name: "Arabic"},
		{Code: "hy", Name: "Armenian"},
		{Code: "as", Name: "Assamese"},
		{Code: "az", Name: "Azerbaijani"},
		{Code: "bn", Name: "Bangla"},
		{Code: "bs", Name: "Bosnian"},
		{Code: "bg", Name: "Bulgarian"},
		{Code: "yue", Name: "Cantonese"},
		{Code: "ca", Name: "Catalan"},
		{Code: "zh-Hans", Name: "Chinese Simplified"},
		{Code: "zh-Hant", Name: "Chinese Traditional"},
		{Code: "hr", Name: "Croatian"},
		{Code: "cs", Name: "Czech"},
		{Code: "da", Name: "Danish"},
		{Code: "prs", Name: "Dari"},
		{Code: "nl", Name: "Dutch"},
		{Code: "en", Name: "English"},
		{Code: "et", Name: "Estonian"},
		{Code: "fj", Name: "Fijian"},
		{Code: "fil", Name: "Filipino"},
		{Code: "fi", Name: "Finnish"},
		{Code: "fr", Name: "French"},
		{Code: "de", Name: "German"},
		{Code: "el", Name: "Greek"},
		{Code: "gu", Name: "Gujarati"},
		{Code: "ht", Name: "Haitian Creole"},
		{Code: "he", Name: "Hebrew"},
		{Code: "hi", Name: "Hindi"},
		{Code: "mww", Name: "Hmong Daw"},
		{Code: "hu", Name: "Hungarian"},
		{Code: "is", Name: "Icelandic"},
		{Code: "id", Name: "Indonesian"},
		{Code: "iu", Name: "Inuktitut"},
		{Code: "ga", Name: "Irish"},
		{Code: "it", Name: "Italian"},
		{Code: "ja", Name: "Japanese"},
		{Code: "kn", Name: "Kannada"},
		{Code: "kk", Name: "Kazakh"},
		{Code: "km", Name: "Khmer"},
		{Code: "tlh-Latn", Name: "Klingon"},
		{Code: "ko", Name: "Korean"},
		{Code: "ku", Name: "Kurdish"},
		{Code: "lo", Name: "Lao"},
		{Code: "lv", Name: "Latvian"},
		{Code: "lt", Name: "Lithuanian"},
		{Code: "mg", Name: "Malagasy"},
		{Code: "ms", Name: "Malay"},
		{Code: "ml", Name: "Malayalam"},
		{Code: "mt", Name: "Maltese"},
		{Code: "mi", Name: "Maori"},
		{Code: "mr", Name: "Marathi"},
		{Code: "my", Name: "Myanmar"},
		{Code: "ne", Name: "Nepali"},
		{Code: "nb", Name: "Norwegian"},
		{Code: "or", Name: "Odia"},
		{Code: "ps", Name: "Pashto"},
		{Code: "fa", Name: "Persian"},
		{Code: "pl", Name: "Polish"},
		{Code: "pt", Name: "Portuguese"},
		{Code: "pa", Name: "Punjabi"},
		{Code: "otq", Name: "Queretaro Otomi"},
		{Code: "ro", Name: "Romanian"},
		{Code: "ru", Name: "Russian"},
		{Code: "sm", Name: "Samoan"},
		{Code: "sr-Cyrl", Name: "Serbian"},
		{Code: "sk", Name: "Slovak"},
		{Code: "sl", Name: "Slovenian"},
		{Code: "es", Name: "Spanish"},
		{Code: "sw", Name: "Swahili"},
		{Code: "sv", Name: "Swedish"},
		{Code: "ty", Name: "Tahitian"},
		{Code: "ta", Name: "Tamil"},
		{Code: "te", Name: "Telugu"},
		{Code: "th", Name: "Thai"},
		{Code: "ti", Name: "Tigrinya"},
		{Code: "to", Name: "Tongan"},
		{Code: "tr", Name: "Turkish"},
		{Code: "uk", Name: "Ukrainian"},
		{Code: "ur", Name: "Urdu"},
		{Code: "vi", Name: "Vietnamese"},
		{Code: "cy", Name: "Welsh"},
		{Code: "yua", Name: "Yucatec Maya"},
	},
}
