package openai

import (
	"github.com/mynaparrot/plugnmeet-protocol/plugnmeet"
	"github.com/mynaparrot/plugnmeet-server/pkg/insights"
)

// supportedLanguages holds the static list of languages for OpenAI services.
// The key is the service name (e.g., "transcription").
// List from: https://developers.openai.com/api/docs/guides/speech-to-text#supported-languages
var supportedLanguages = map[insights.ServiceType][]plugnmeet.InsightsSupportedLangInfo{
	insights.ServiceTypeTranscription: {
		{Code: "af", Name: "Afrikaans", Locale: "af"},
		{Code: "ar", Name: "Arabic", Locale: "ar"},
		{Code: "hy", Name: "Armenian", Locale: "hy"},
		{Code: "az", Name: "Azerbaijani", Locale: "az"},
		{Code: "be", Name: "Belarusian", Locale: "be"},
		{Code: "bs", Name: "Bosnian", Locale: "bs"},
		{Code: "bg", Name: "Bulgarian", Locale: "bg"},
		{Code: "ca", Name: "Catalan", Locale: "ca"},
		{Code: "zh", Name: "Chinese", Locale: "zh"},
		{Code: "hr", Name: "Croatian", Locale: "hr"},
		{Code: "cs", Name: "Czech", Locale: "cs"},
		{Code: "da", Name: "Danish", Locale: "da"},
		{Code: "nl", Name: "Dutch", Locale: "nl"},
		{Code: "en", Name: "English", Locale: "en"},
		{Code: "et", Name: "Estonian", Locale: "et"},
		{Code: "fi", Name: "Finnish", Locale: "fi"},
		{Code: "fr", Name: "French", Locale: "fr"},
		{Code: "gl", Name: "Galician", Locale: "gl"},
		{Code: "de", Name: "German", Locale: "de"},
		{Code: "el", Name: "Greek", Locale: "el"},
		{Code: "he", Name: "Hebrew", Locale: "he"},
		{Code: "hi", Name: "Hindi", Locale: "hi"},
		{Code: "hu", Name: "Hungarian", Locale: "hu"},
		{Code: "is", Name: "Icelandic", Locale: "is"},
		{Code: "id", Name: "Indonesian", Locale: "id"},
		{Code: "it", Name: "Italian", Locale: "it"},
		{Code: "ja", Name: "Japanese", Locale: "ja"},
		{Code: "kn", Name: "Kannada", Locale: "kn"},
		{Code: "kk", Name: "Kazakh", Locale: "kk"},
		{Code: "ko", Name: "Korean", Locale: "ko"},
		{Code: "lv", Name: "Latvian", Locale: "lv"},
		{Code: "lt", Name: "Lithuanian", Locale: "lt"},
		{Code: "mk", Name: "Macedonian", Locale: "mk"},
		{Code: "ms", Name: "Malay", Locale: "ms"},
		{Code: "mr", Name: "Marathi", Locale: "mr"},
		{Code: "mi", Name: "Maori", Locale: "mi"},
		{Code: "ne", Name: "Nepali", Locale: "ne"},
		{Code: "no", Name: "Norwegian", Locale: "no"},
		{Code: "fa", Name: "Persian", Locale: "fa"},
		{Code: "pl", Name: "Polish", Locale: "pl"},
		{Code: "pt", Name: "Portuguese", Locale: "pt"},
		{Code: "ro", Name: "Romanian", Locale: "ro"},
		{Code: "ru", Name: "Russian", Locale: "ru"},
		{Code: "sr", Name: "Serbian", Locale: "sr"},
		{Code: "sk", Name: "Slovak", Locale: "sk"},
		{Code: "sl", Name: "Slovenian", Locale: "sl"},
		{Code: "es", Name: "Spanish", Locale: "es"},
		{Code: "sw", Name: "Swahili", Locale: "sw"},
		{Code: "sv", Name: "Swedish", Locale: "sv"},
		{Code: "tl", Name: "Tagalog", Locale: "tl"},
		{Code: "ta", Name: "Tamil", Locale: "ta"},
		{Code: "th", Name: "Thai", Locale: "th"},
		{Code: "tr", Name: "Turkish", Locale: "tr"},
		{Code: "uk", Name: "Ukrainian", Locale: "uk"},
		{Code: "ur", Name: "Urdu", Locale: "ur"},
		{Code: "vi", Name: "Vietnamese", Locale: "vi"},
		{Code: "cy", Name: "Welsh", Locale: "cy"},
	},
	// For translation, OpenAI models can handle a wide variety of languages.
	// We can reuse the same list as a good starting point for the UI.
	insights.ServiceTypeTranslation: {
		{Code: "af", Name: "Afrikaans", Locale: "af"},
		{Code: "ar", Name: "Arabic", Locale: "ar"},
		{Code: "hy", Name: "Armenian", Locale: "hy"},
		{Code: "az", Name: "Azerbaijani", Locale: "az"},
		{Code: "be", Name: "Belarusian", Locale: "be"},
		{Code: "bs", Name: "Bosnian", Locale: "bs"},
		{Code: "bg", Name: "Bulgarian", Locale: "bg"},
		{Code: "ca", Name: "Catalan", Locale: "ca"},
		{Code: "zh", Name: "Chinese", Locale: "zh"},
		{Code: "hr", Name: "Croatian", Locale: "hr"},
		{Code: "cs", Name: "Czech", Locale: "cs"},
		{Code: "da", Name: "Danish", Locale: "da"},
		{Code: "nl", Name: "Dutch", Locale: "nl"},
		{Code: "en", Name: "English", Locale: "en"},
		{Code: "et", Name: "Estonian", Locale: "et"},
		{Code: "fi", Name: "Finnish", Locale: "fi"},
		{Code: "fr", Name: "French", Locale: "fr"},
		{Code: "gl", Name: "Galician", Locale: "gl"},
		{Code: "de", Name: "German", Locale: "de"},
		{Code: "el", Name: "Greek", Locale: "el"},
		{Code: "he", Name: "Hebrew", Locale: "he"},
		{Code: "hi", Name: "Hindi", Locale: "hi"},
		{Code: "hu", Name: "Hungarian", Locale: "hu"},
		{Code: "is", Name: "Icelandic", Locale: "is"},
		{Code: "id", Name: "Indonesian", Locale: "id"},
		{Code: "it", Name: "Italian", Locale: "it"},
		{Code: "ja", Name: "Japanese", Locale: "ja"},
		{Code: "kn", Name: "Kannada", Locale: "kn"},
		{Code: "kk", Name: "Kazakh", Locale: "kk"},
		{Code: "ko", Name: "Korean", Locale: "ko"},
		{Code: "lv", Name: "Latvian", Locale: "lv"},
		{Code: "lt", Name: "Lithuanian", Locale: "lt"},
		{Code: "mk", Name: "Macedonian", Locale: "mk"},
		{Code: "ms", Name: "Malay", Locale: "ms"},
		{Code: "mr", Name: "Marathi", Locale: "mr"},
		{Code: "mi", Name: "Maori", Locale: "mi"},
		{Code: "ne", Name: "Nepali", Locale: "ne"},
		{Code: "no", Name: "Norwegian", Locale: "no"},
		{Code: "fa", Name: "Persian", Locale: "fa"},
		{Code: "pl", Name: "Polish", Locale: "pl"},
		{Code: "pt", Name: "Portuguese", Locale: "pt"},
		{Code: "ro", Name: "Romanian", Locale: "ro"},
		{Code: "ru", Name: "Russian", Locale: "ru"},
		{Code: "sr", Name: "Serbian", Locale: "sr"},
		{Code: "sk", Name: "Slovak", Locale: "sk"},
		{Code: "sl", Name: "Slovenian", Locale: "sl"},
		{Code: "es", Name: "Spanish", Locale: "es"},
		{Code: "sw", Name: "Swahili", Locale: "sw"},
		{Code: "sv", Name: "Swedish", Locale: "sv"},
		{Code: "tl", Name: "Tagalog", Locale: "tl"},
		{Code: "ta", Name: "Tamil", Locale: "ta"},
		{Code: "th", Name: "Thai", Locale: "th"},
		{Code: "tr", Name: "Turkish", Locale: "tr"},
		{Code: "uk", Name: "Ukrainian", Locale: "uk"},
		{Code: "ur", Name: "Urdu", Locale: "ur"},
		{Code: "vi", Name: "Vietnamese", Locale: "vi"},
		{Code: "cy", Name: "Welsh", Locale: "cy"},
	},
}
