package openai

import (
	"github.com/mynaparrot/plugnmeet-protocol/plugnmeet"
	"github.com/mynaparrot/plugnmeet-server/pkg/insights"
)

// supportedLanguages holds the static list of languages for OpenAI services.
// The key is the service name (e.g., "transcription").
// List from: https://developers.openai.com/api/docs/guides/speech-to-text#supported-languages
// Highly optimized with localized script splits for complex international scripts.
var supportedLanguages = map[insights.ServiceType][]plugnmeet.InsightsSupportedLangInfo{
	insights.ServiceTypeTranscription: {
		{Code: "af", Name: "Afrikaans", Locale: "af"},
		{Code: "sq", Name: "Albanian", Locale: "sq"},
		{Code: "am", Name: "Amharic", Locale: "am"},
		{Code: "ar", Name: "Arabic", Locale: "ar"},
		{Code: "hy", Name: "Armenian", Locale: "hy"},
		{Code: "az", Name: "Azerbaijani", Locale: "az"},
		{Code: "eu", Name: "Basque", Locale: "eu"},
		{Code: "be", Name: "Belarusian", Locale: "be"},
		{Code: "bn", Name: "Bengali", Locale: "bn"},
		{Code: "bs", Name: "Bosnian", Locale: "bs"},
		{Code: "bg", Name: "Bulgarian", Locale: "bg"},
		{Code: "ca", Name: "Catalan", Locale: "ca"},
		{Code: "zh-Hans", Name: "Chinese (Simplified)", Locale: "zh-Hans"},
		{Code: "zh-Hant", Name: "Chinese (Traditional)", Locale: "zh-Hant"},
		{Code: "hr", Name: "Croatian", Locale: "hr"},
		{Code: "cs", Name: "Czech", Locale: "cs"},
		{Code: "da", Name: "Danish", Locale: "da"},
		{Code: "nl", Name: "Dutch", Locale: "nl"},
		{Code: "en-US", Name: "English (US)", Locale: "en-US"},
		{Code: "en-GB", Name: "English (UK)", Locale: "en-GB"},
		{Code: "et", Name: "Estonian", Locale: "et"},
		{Code: "fi", Name: "Finnish", Locale: "fi"},
		{Code: "fr", Name: "French", Locale: "fr"},
		{Code: "gl", Name: "Galician", Locale: "gl"},
		{Code: "ka", Name: "Georgian", Locale: "ka"},
		{Code: "de", Name: "German", Locale: "de"},
		{Code: "el", Name: "Greek", Locale: "el"},
		{Code: "gu", Name: "Gujarati", Locale: "gu"},
		{Code: "ht", Name: "Haitian Creole", Locale: "ht"},
		{Code: "he", Name: "Hebrew", Locale: "he"},
		{Code: "hi", Name: "Hindi", Locale: "hi"},
		{Code: "hu", Name: "Hungarian", Locale: "hu"},
		{Code: "is", Name: "Icelandic", Locale: "is"},
		{Code: "id", Name: "Indonesian", Locale: "id"},
		{Code: "it", Name: "Italian", Locale: "it"},
		{Code: "ja", Name: "Japanese", Locale: "ja"},
		{Code: "jw", Name: "Javanese", Locale: "jw"},
		{Code: "kn", Name: "Kannada", Locale: "kn"},
		{Code: "kk", Name: "Kazakh", Locale: "kk"},
		{Code: "km", Name: "Khmer", Locale: "km"},
		{Code: "ko", Name: "Korean", Locale: "ko"},
		{Code: "la", Name: "Latin", Locale: "la"},
		{Code: "lv", Name: "Latvian", Locale: "lv"},
		{Code: "lt", Name: "Lithuanian", Locale: "lt"},
		{Code: "mk", Name: "Macedonian", Locale: "mk"},
		{Code: "ms", Name: "Malay", Locale: "ms"},
		{Code: "ml", Name: "Malayalam", Locale: "ml"},
		{Code: "mr", Name: "Marathi", Locale: "mr"},
		{Code: "mi", Name: "Maori", Locale: "mi"},
		{Code: "mn", Name: "Mongolian", Locale: "mn"},
		{Code: "my", Name: "Myanmar", Locale: "my"},
		{Code: "ne", Name: "Nepali", Locale: "ne"},
		{Code: "no", Name: "Norwegian", Locale: "no"},
		{Code: "fa", Name: "Persian", Locale: "fa"},
		{Code: "pl", Name: "Polish", Locale: "pl"},
		{Code: "pt-BR", Name: "Portuguese (Brazil)", Locale: "pt-BR"},
		{Code: "pt-PT", Name: "Portuguese (Portugal)", Locale: "pt-PT"},
		{Code: "pa", Name: "Punjabi", Locale: "pa"},
		{Code: "ro", Name: "Romanian", Locale: "ro"},
		{Code: "ru", Name: "Russian", Locale: "ru"},
		{Code: "sa", Name: "Sanskrit", Locale: "sa"},
		{Code: "sr", Name: "Serbian", Locale: "sr"},
		{Code: "sd", Name: "Sindhi", Locale: "sd"},
		{Code: "si", Name: "Sinhala", Locale: "si"},
		{Code: "sk", Name: "Slovak", Locale: "sk"},
		{Code: "sl", Name: "Slovenian", Locale: "sl"},
		{Code: "so", Name: "Somali", Locale: "so"},
		{Code: "es", Name: "Spanish", Locale: "es"},
		{Code: "su", Name: "Sundanese", Locale: "su"},
		{Code: "sw", Name: "Swahili", Locale: "sw"},
		{Code: "sv", Name: "Swedish", Locale: "sv"},
		{Code: "tl", Name: "Tagalog", Locale: "tl"},
		{Code: "tg", Name: "Tajik", Locale: "tg"},
		{Code: "ta", Name: "Tamil", Locale: "ta"},
		{Code: "te", Name: "Telugu", Locale: "te"},
		{Code: "th", Name: "Thai", Locale: "th"},
		{Code: "tr", Name: "Turkish", Locale: "tr"},
		{Code: "uk", Name: "Ukrainian", Locale: "uk"},
		{Code: "ur", Name: "Urdu", Locale: "ur"},
		{Code: "uz", Name: "Uzbek", Locale: "uz"},
		{Code: "vi", Name: "Vietnamese", Locale: "vi"},
		{Code: "cy", Name: "Welsh", Locale: "cy"},
		{Code: "yo", Name: "Yoruba", Locale: "yo"},
	},
	// Explicit script splits configured for target text engine parsing consistency.
	insights.ServiceTypeTranslation: {
		{Code: "af", Name: "Afrikaans", Locale: "af"},
		{Code: "sq", Name: "Albanian", Locale: "sq"},
		{Code: "am", Name: "Amharic", Locale: "am"},
		{Code: "ar", Name: "Arabic", Locale: "ar"},
		{Code: "hy", Name: "Armenian", Locale: "hy"},
		{Code: "az", Name: "Azerbaijani", Locale: "az"},
		{Code: "eu", Name: "Basque", Locale: "eu"},
		{Code: "be", Name: "Belarusian", Locale: "be"},
		{Code: "bn", Name: "Bengali", Locale: "bn"},
		{Code: "bs", Name: "Bosnian", Locale: "bs"},
		{Code: "bg", Name: "Bulgarian", Locale: "bg"},
		{Code: "ca", Name: "Catalan", Locale: "ca"},
		{Code: "zh-Hans", Name: "Chinese (Simplified)", Locale: "zh-Hans"},
		{Code: "zh-Hant", Name: "Chinese (Traditional)", Locale: "zh-Hant"},
		{Code: "hr", Name: "Croatian", Locale: "hr"},
		{Code: "cs", Name: "Czech", Locale: "cs"},
		{Code: "da", Name: "Danish", Locale: "da"},
		{Code: "nl", Name: "Dutch", Locale: "nl"},
		{Code: "en-US", Name: "English (US)", Locale: "en-US"},
		{Code: "en-GB", Name: "English (UK)", Locale: "en-GB"},
		{Code: "et", Name: "Estonian", Locale: "et"},
		{Code: "fi", Name: "Finnish", Locale: "fi"},
		{Code: "fr", Name: "French", Locale: "fr"},
		{Code: "gl", Name: "Galician", Locale: "gl"},
		{Code: "ka", Name: "Georgian", Locale: "ka"},
		{Code: "de", Name: "German", Locale: "de"},
		{Code: "el", Name: "Greek", Locale: "el"},
		{Code: "gu", Name: "Gujarati", Locale: "gu"},
		{Code: "ht", Name: "Haitian Creole", Locale: "ht"},
		{Code: "he", Name: "Hebrew", Locale: "he"},
		{Code: "hi", Name: "Hindi", Locale: "hi"},
		{Code: "hu", Name: "Hungarian", Locale: "hu"},
		{Code: "is", Name: "Icelandic", Locale: "is"},
		{Code: "id", Name: "Indonesian", Locale: "id"},
		{Code: "it", Name: "Italian", Locale: "it"},
		{Code: "ja", Name: "Japanese", Locale: "ja"},
		{Code: "jw", Name: "Javanese", Locale: "jw"},
		{Code: "kn", Name: "Kannada", Locale: "kn"},
		{Code: "kk", Name: "Kazakh", Locale: "kk"},
		{Code: "km", Name: "Khmer", Locale: "km"},
		{Code: "ko", Name: "Korean", Locale: "ko"},
		{Code: "la", Name: "Latin", Locale: "la"},
		{Code: "lv", Name: "Latvian", Locale: "lv"},
		{Code: "lt", Name: "Lithuanian", Locale: "lt"},
		{Code: "mk", Name: "Macedonian", Locale: "mk"},
		{Code: "ms", Name: "Malay", Locale: "ms"},
		{Code: "ml", Name: "Malayalam", Locale: "ml"},
		{Code: "mr", Name: "Marathi", Locale: "mr"},
		{Code: "mi", Name: "Maori", Locale: "mi"},
		{Code: "mn", Name: "Mongolian", Locale: "mn"},
		{Code: "my", Name: "Myanmar", Locale: "my"},
		{Code: "ne", Name: "Nepali", Locale: "ne"},
		{Code: "no", Name: "Norwegian", Locale: "no"},
		{Code: "fa", Name: "Persian", Locale: "fa"},
		{Code: "pl", Name: "Polish", Locale: "pl"},
		{Code: "pt-BR", Name: "Portuguese (Brazil)", Locale: "pt-BR"},
		{Code: "pt-PT", Name: "Portuguese (Portugal)", Locale: "pt-PT"},
		{Code: "pa", Name: "Punjabi", Locale: "pa"},
		{Code: "ro", Name: "Romanian", Locale: "ro"},
		{Code: "ru", Name: "Russian", Locale: "ru"},
		{Code: "sa", Name: "Sanskrit", Locale: "sa"},
		{Code: "sr", Name: "Serbian", Locale: "sr"},
		{Code: "sd", Name: "Sindhi", Locale: "sd"},
		{Code: "si", Name: "Sinhala", Locale: "si"},
		{Code: "sk", Name: "Slovak", Locale: "sk"},
		{Code: "sl", Name: "Slovenian", Locale: "sl"},
		{Code: "so", Name: "Somali", Locale: "so"},
		{Code: "es", Name: "Spanish", Locale: "es"},
		{Code: "su", Name: "Sundanese", Locale: "su"},
		{Code: "sw", Name: "Swahili", Locale: "sw"},
		{Code: "sv", Name: "Swedish", Locale: "sv"},
		{Code: "tl", Name: "Tagalog", Locale: "tl"},
		{Code: "tg", Name: "Tajik", Locale: "tg"},
		{Code: "ta", Name: "Tamil", Locale: "ta"},
		{Code: "te", Name: "Telugu", Locale: "te"},
		{Code: "th", Name: "Thai", Locale: "th"},
		{Code: "tr", Name: "Turkish", Locale: "tr"},
		{Code: "uk", Name: "Ukrainian", Locale: "uk"},
		{Code: "ur", Name: "Urdu", Locale: "ur"},
		{Code: "uz", Name: "Uzbek", Locale: "uz"},
		{Code: "vi", Name: "Vietnamese", Locale: "vi"},
		{Code: "cy", Name: "Welsh", Locale: "cy"},
		{Code: "yo", Name: "Yoruba", Locale: "yo"},
	},
}
